server:
    port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: guides
          predicates:
            - Path=/guides
            - After= 2025-09-02T00:00:00.000-00:00[Asia/Jerusalem]
          uri: https://spring.io
        - id: ido
          predicates:
            - Path=/udemy
          uri: https://udemy.com
